# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a02b598034f09fcf7e48dcf7e7e192fa6987c392f99be7be236af67a0f9f218c4c82fb31a087bc4f10e818f5eba24f8092df7c0e0d544a74099ff342c9beb31

test:
  secret_key_base: 44b3dfbb7b7c009f47e160b4b7b130ef92a49e75a57c681ad100c14ac7c51775e032e4627a06caf98d81fa3b5aafcbdf75cfcee0df90ae5dfc8a80bfee53a7e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
